### ISSUE TITLE
go get 时发生包含错误

### ISSUE THREAD

**Issue by anlityli** [pili-engineering/pili-sdk-go.v2#5]
![image](https://user-images.githubusercontent.com/11658297/75943734-cafce000-5ed0-11ea-8b7d-a6eac769842c.png)
在执行```go get github.com/pili-engineering/pili-sdk-go.v2/pili```发生的错误
```
go: finding github.com/pili-engineering/pili-sdk-go.v2 latest
../../../GoPath/pkg/mod/github.com/pili-engineering/pili-sdk-go.v2@v0.0.0-20190923072324-f424329f4f73/pili/auth.go:10:2: module github.com/qiniu/x@latest (v7.0.8+incompatible) found, but does not contain package github.com/qiniu/x/bytes/seekable
```

**Comment by snyh** [comment]
应该是 github.com/qiniu/x 没处理好。
目前可以在自己项目里的go.mod加上

`replace github.com/qiniu/x => github.com/qiniu/x v0.0.0-20190911131702-ec64d9399366 // indirect
`
来workaround
